### ISSUE TITLE
Adding Angular Courses for Beginners

### ISSUE THREAD

**Issue by r0cketr1kky** [Anki7s/Angular#13]
Links to Angular courses can be added in the links or they could be added a different sub-heading called "Courses" so that beginners like me can easily look up the right resources to learn Angular JS. Some users may pay for the courses if they want to get into the depth of learning Angular.

A few paid courses that are considered great (in decreasing order) :
1. **Angular and NodeJS - The Mean Stack Guide** (https://www.udemy.com/course/angular-2-and-nodejs-the-practical-guide/?LSNPUBID=jU79Zysihs4&ranEAID=jU79Zysihs4&ranMID=39197&ranSiteID=jU79Zysihs4-rJw2OvTgG9qeT8xdaxcRPQ)

2. **Shaping up with AngularJS** - (https://www.pluralsight.com/courses/angularjs-get-started?clickid=Xj8ySQXa4xyJW5zwUx0Mo3QzUkn2vHxeFz3s1w0&irgwc=1&mpid=1419154&utm_source=impactradius&utm_medium=digital_affiliate&utm_campaign=1419154&aid=7010a000001xAKZAA2)

3. **Angular 8 The Complete Guide** - (https://www.udemy.com/course/the-complete-guide-to-angular-2/?LSNPUBID=jU79Zysihs4&ranEAID=jU79Zysihs4&ranMID=39197&ranSiteID=jU79Zysihs4-VIh0RH5MxSrf2kWMlXlH2A)

**Comment by thedevankit-0** [comment]
please make a pr.
